# Generated by Django 2.2.5 on 2021-01-31 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='closed',
            field=models.TimeField(auto_now=True),
        ),
    ]
