# Generated by Django 2.2.5 on 2021-01-31 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_auto_20210131_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='closed',
            field=models.TimeField(),
        ),
    ]
