# Generated by Django 2.2.5 on 2021-01-31 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_auto_20210131_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='closed',
            field=models.DateTimeField(),
        ),
    ]
