# Generated by Django 2.2.5 on 2021-01-31 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_auto_20210131_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='immaterial',
            fields=[
                ('purchase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='purchases.Purchase')),
            ],
            options={
                'abstract': False,
            },
            bases=('purchases.purchase',),
        ),
        migrations.CreateModel(
            name='material',
            fields=[
                ('purchase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='purchases.Purchase')),
                ('unit', models.CharField(blank=True, choices=[('kg', 'Kg'), ('g', 'g')], max_length=5)),
                ('total', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('purchases.purchase',),
        ),
    ]
